name: Build and Deploy
on:
    push:
        branches:
            - gh-pages
    
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install dependencies
              run: |
                yarn global add gatsby
                yarn global add gh-pages


            - name: Build and deploy
              run: gatsby build && gh-pages -d public -a
